### PR TITLE
Adds the various Alaska Wildfire map layers to an automated Prefect script

### PR DESCRIPTION
**Pull request by BobTorgerson**
This PR contains 3 new Prefect scripts for generating the 5 daily updated layers for our [Alaska Wildfire Explorer map](https://snap.uaf.edu/tools/alaska-wildfires). 

**Smokey Bear Layers**
There are two layers we refer to as the "Smokey Bear" layers that continue to use their original code for generating the underlying GeoTIFFs (spruceadj_3338.tif and snow_cover_3338.tif), but can now be automated through our production Prefect server by running the Prefect client flows in smokey_bear/smokey_bear_layer.py & smokey_bear/snow_cover_layer.py

Both of these are available as working flows on our production server currently, and if run, they will regenerate the GeoTIFFs with the latest day's data. Due to the need for an admin password for accessing the data that Chris has provided for us, I have used a tool previously unused in Prefect called "blocks" which are essentially encrypted password holders that can be called at run-time by the Prefect scripts.

**2024 Fires, Lightning Strikes in the past 36 hours, and VIIRS hotspots in the past 48 hours**
These three layers have undergone a major change as previously the updated fires and VIIRS hotspots were coming from their own service called mv-aicc-fire-shim as GeoJSON and the lightning strikes were coming from an AICC endpoint too, but being placed into a PostGIS database which was made available through our production Geoserver instance. The desire was to reduce the number of managed services, and ridding ourselves of both this "shim" code for creating GeoJSON output expected by our Alaska Wildfires code along with a PostGIS instance running in the cloud is a major win.

Firstly, I have done away with GeoJSON and the need for PostGIS entirely by collecting the most recent data and generating a number of shapefiles that are served via our production GeoServer instance. The script to generate the 4 shapefiles with their associated metadata properties is all contained within the file "get_current_fire_layers.py". The code runs through the 3 desired layers to generate 2 shapefiles for the updated fires (one for points, and another for polygons), 1 shapefile for the VIIRS hot spots, and 1 for the most recent lightning strikes. 

To make running this script automated, I have made a simple Prefect client flow called "current_fire_layers.py" which is running on our production GeoServer and can be re-run at any time to update the most recent data. This could be done any number of times per day, including running every hour for example to update the available data on the Alaska Wildfire Explorer map.

Due to the fact that we are starting this work in late winter, before there are any notable fires, I have spoofed data from last year that is available in the data/debug directory and gives an example of the expected GeoJSON that is provided from the services when they have data to return. This feature can be easily turned off to request data from the live remote services by simply changing the "debug" parameters to "False". 

**Testing the Prefect flow**
To test these flows, you can find the underlying data that is used by GeoServer in the directory /usr/share/geoserver/data_dir/data/alaska_wildfires/ where the smokey bear layers are in that directory as "spruceadj_3338.tif" and "snow_cover_3338.tif" and the rest of the generated shapefiles are all within the "fire_layers" directory.

When you run any of these Prefect flows, when it is complete, I would expect to see a new timestamp added to the expected layer, even if the new data is still using the debug data. A true test will be when we can start to collect real fire and lightning data, but fingers crossed that is several months away.

As always, please ask questions if anything doesn't make sense!

### CODE REVIEW

**Review by cstephen — COMMENTED** [review]
I successfully ran each of these deployments on our Prefect server:

- snow_cover_layer
- smokey_bear_layer
- current_fire_layers 

I verified that the file timestamps changed for all relevant files on our GeoServer server, and that the corresponding branch of the Alaska Wildfire Explorer (https://github.com/ua-snap/alaska-wildfires/pull/51) accessed and displayed all corresponding layers properly.

The deployment script code looks good & makes sense! But should these scripts also be included in this PR?

- update_smokey_bear.sh
- update_snow_cover.sh

**Comment by BobTorgerson** [comment]
That's a good question @cstephen! I had to write this new script for the other fire layers, but the smokey bear and snow cover layers were already created scripts previously. I've gone ahead and modified the Prefect flows to use local scripts rather than download a remote Github repository to get those scripts. 

I also am making these into subflows for a larger overall flow that runs all 5 layers together.

**Comment by BobTorgerson** [comment]
@cstephen Boy, that was a bit more of a mess than I had expected. I got it working though, and now everything is running as subflows of a new flow with the title "Update Wildfire Layers". Try running that deployment in the production server to see it create subflows from the individual flows and execute them sequentially. 

Additionally, the subflows can be made from flows, which I wasn't aware of previously, so we can still run each of these flows as a standalone flow, but they will automatically be converted to subflows when executed from an overarching flow.

**Review by cstephen — APPROVED** [review]
Everything looks good to me 👍 

I successfully ran the new "Update Wildfire Layers" flow and saw it run all of its subflows through the graph interface (very slick), and confirmed that the corresponding file timestamps got updated on GeoServer. I also peaked at the code of the `update_wildfire_map.py` file and it's easy to follow how it controls the execution of subflows.

Thanks for adding `update_smokey_bear.sh` and `update_snow_cover.sh` to the repo, also!

**Pull request merged**
